# Generated by Django 5.0.1 on 2026-02-04 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_conversation_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(max_length=10)),
                ("path", models.TextField()),
                ("user_agent", models.TextField(blank=True)),
                ("status_code", models.IntegerField()),
                ("was_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="chatbot_req_created_9bc35b_idx"
                    ),
                    models.Index(
                        fields=["user"], name="chatbot_req_user_id_87a1aa_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="chatbot_req_ip_addr_1f7d3f_idx"
                    ),
                ],
            },
        ),
    ]
